version: "3.8"

networks:
  mongo-cluster:

services:
  megabot-db:
    image: mongo:5
    restart: always
    command: mongod --replSet rs1 --bind_ip localhost,megabot-db
    healthcheck:
      test: test $$(echo "rs.initiate({_id:\"rs1\", members:[{_id:0, host:\"megabot-db\"}]}).ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    networks:
      - mongo-cluster
    ports:
      - 27017:27017
    volumes:
      - mongo-db-volume:/data/db

volumes:
  mongo-db-volume:
